// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Main$TicTacToe = require("./Main.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Main$TicTacToe.make(/* array */[])), "index");

/*  Not a pure module */
